server:
  port: 6061
spring:
  application:
    #应用名
    name: zuul-server
eureka:
  client:
    service-url:
      defaultZone: http://localhost:10086/eureka
#zull配置
zuul:
  routes:
    api-a:
      path: /api-a/**
      serviceId: consumer-demo
    api-b:
      path: /api-b/**
      serviceId: consumer-feign
